server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: POST-SERVICE
          uri: lb://POST-SERVICE     # ✅ MUST MATCH Eureka service name exactly (case-sensitive)
          predicates:
            - Path=/api/posts/**

        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE          # ✅ MATCH Eureka service name
          predicates:
            - Path=/api/comments/**

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
